[workspace]
members = ["runtime/novovm-host"]
default-members = ["runtime/novovm-host"]
exclude = ["legacy/supervm-20261002"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.94"
publish = false

[workspace.dependencies]
anyhow = "=1.0.103"
sha2 = "=0.10.9"

[profile.release]
overflow-checks = true

[profile.test]
debug-assertions = true
overflow-checks = true
