"""
SuperVM Work Logger - Work Note Generator
工作笔记生成器（Markdown 输出）
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List

def format_duration(seconds: int) -> str:
    """格式化时长"""
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60
    
    if hours > 0:
        return f"{hours}h {minutes}m {secs}s"
    elif minutes > 0:
        return f"{minutes}m {secs}s"
    else:
        return f"{secs}s"

def generate_work_note(session_id: str, start_time: datetime, duration: int, 
                       file_changes: Dict[str, Dict], output_path: Path,
                       work_note_data: Dict = None) -> Path:
    """
    生成工作笔记
    
    Args:
        session_id: 会话 ID
        start_time: 开始时间
        duration: 持续时长（秒）
        file_changes: 文件变更字典
        output_path: 输出目录
        work_note_data: 用户输入的工作内容
    
    Returns:
        生成的文件路径
    """
    # 生成文件名
    date_str = start_time.strftime('%Y-%m-%d')
    filename = f"WORK-NOTE-{date_str}-{session_id}.md"
    file_path = output_path / filename
    
    # 计算统计数据
    total_files = len(file_changes)
    total_added = sum(c['lines_added'] for c in file_changes.values())
    total_removed = sum(c['lines_removed'] for c in file_changes.values())
    
    # 按类型分组
    created = []
    modified = []
    deleted = []
    
    for path, change in file_changes.items():
        if change['type'] == 'created':
            created.append((path, change))
        elif change['type'] == 'deleted':
            deleted.append((path, change))
        else:
            modified.append((path, change))
    
    # 生成 Markdown
    content = f"""# Work Note - Session {session_id}

**Date**: {start_time.strftime('%Y-%m-%d %H:%M:%S')}  
**Duration**: {format_duration(duration)}  
**Status**: ✅ Completed

---

## � Work Summary

"""
    
    # 添加用户输入的工作内容
    if work_note_data:
        if work_note_data.get('summary'):
            content += f"**今日工作**: {work_note_data['summary']}\n\n"
        
        if work_note_data.get('problems'):
            content += f"### 🔴 遇到的问题\n\n{work_note_data['problems']}\n\n"
        
        if work_note_data.get('solutions'):
            content += f"### ✅ 解决方案\n\n{work_note_data['solutions']}\n\n"
        
        if work_note_data.get('chat'):
            content += f"### 💬 与 Copilot 的关键对话\n\n"
            for chat in work_note_data['chat'].split(';'):
                if chat.strip():
                    content += f"- {chat.strip()}\n"
            content += "\n"
        
        if work_note_data.get('next_steps'):
            content += f"### 📋 下一步计划\n\n{work_note_data['next_steps']}\n\n"
    else:
        content += "_（未填写工作内容）_\n\n"
    
    content += """---

## �📊 Statistics

| Metric | Value |
|--------|-------|
| Files Changed | {total_files} |
| Lines Added | {total_added} |
| Lines Removed | {total_removed} |
| Net Change | {total_added - total_removed:+d} |

---

## 📂 Files Changed

"""
    
    # Created files
    if created:
        content += "### ✅ Created\n\n"
        for path, change in sorted(created):
            lines = change['lines_added']
            content += f"- `{path}` (+{lines} lines)\n"
        content += "\n"
    
    # Modified files
    if modified:
        content += "### ✏️ Modified\n\n"
        for path, change in sorted(modified):
            added = change['lines_added']
            removed = change['lines_removed']
            content += f"- `{path}` (+{added} -{removed} lines)\n"
        content += "\n"
    
    # Deleted files
    if deleted:
        content += "### ❌ Deleted\n\n"
        for path, change in deleted:
            content += f"- `{path}`\n"
        content += "\n"
    
    # 添加验证清单
    content += """---

## ✅ Verification Checklist

- [ ] Code compiles without errors
- [ ] Tests pass
- [ ] Documentation updated
- [ ] No sensitive data committed
- [ ] Performance benchmarks (if applicable)

---

## 📝 Notes

<!-- Add your notes here -->

---

**Generated by**: SuperVM Work Logger (Python Edition)  
**Generated at**: {generated_time}
""".format(generated_time=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    
    # 写入文件
    output_path.mkdir(parents=True, exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return file_path
