use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EffectiveUpConfig {
    pub profile: String,
    pub role_profile: String,
    pub overlay_route_runtime_file: Option<String>,
    pub overlay_route_runtime_profile: Option<String>,
    pub overlay_route_mode: Option<String>,
    pub overlay_route_relay_directory_file: Option<String>,
    pub policy_bin: String,
    pub node_bin: String,
    pub use_node_watch_mode: bool,
    pub poll_ms: Option<u64>,
    pub node_watch_batch_max_files: Option<usize>,
    pub idle_exit_seconds: Option<u64>,
    pub no_gateway: bool,
    pub lean_io: bool,
    pub supervisor_poll_ms: Option<u64>,
    pub gateway_bind: Option<String>,
    pub gateway_spool_dir: Option<String>,
    pub gateway_max_requests: Option<u32>,
    pub ops_wire_dir: Option<String>,
    pub ops_wire_watch_done_dir: Option<String>,
    pub ops_wire_watch_failed_dir: Option<String>,
    pub ops_wire_watch_drop_failed: bool,
    pub auto_profile_state_file: Option<String>,
    pub auto_profile_profiles: Option<String>,
    pub auto_profile_min_hold_seconds: Option<u64>,
    pub auto_profile_switch_margin: Option<f64>,
    pub auto_profile_switchback_cooldown_seconds: Option<u64>,
    pub auto_profile_recheck_seconds: Option<u64>,
    pub auto_profile_enabled: bool,
    pub skip_policy_warmup: bool,
    pub foreground: bool,
    pub dry_run: bool,
    pub audit_file: Option<String>,
    pub log_file: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutoProfileDecision {
    pub action: String,
    pub selected_profile: Option<String>,
    pub selected_region: Option<String>,
    pub reason: String,
    pub score: Option<f64>,
    pub next_recheck_after_seconds: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpAuditRecord {
    pub profile: String,
    pub role_profile: String,
    pub policy_bin: String,
    pub node_bin: String,
    pub overlay_route_runtime_file: Option<String>,
    pub overlay_route_runtime_profile: Option<String>,
    pub overlay_route_mode: Option<String>,
    pub overlay_route_relay_directory_file: Option<String>,
    pub use_node_watch_mode: bool,
    pub poll_ms: Option<u64>,
    pub node_watch_batch_max_files: Option<usize>,
    pub idle_exit_seconds: Option<u64>,
    pub auto_profile_state_file: Option<String>,
    pub auto_profile_profiles: Option<String>,
    pub auto_profile_min_hold_seconds: Option<u64>,
    pub auto_profile_switch_margin: Option<f64>,
    pub auto_profile_switchback_cooldown_seconds: Option<u64>,
    pub auto_profile_recheck_seconds: Option<u64>,
    pub auto_profile_decision: Option<AutoProfileDecision>,
    pub dry_run: bool,
    pub launched: bool,
    pub reason: String,
}
